---
title: "NOAA Data"
output: html_notebook
html_document: NOAA_Data.html
---

The ground based ASOS stations of airports have a historical repository here: ftp://ftp.ncdc.noaa.gov/pub/data/noaa/

Some quotes from the readme.txt:

"This directory contains ISH/ISD data in directories 
! by year.  
Please note that ISH and ISD refer to the same data--
Integrated Surface Data, sometimes called 
Integrated Surface Hourly."

"The filenames correspond with the station numbers listed in the ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.txt file (and in
ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.csv )
or http://www1.ncdc.noaa.gov/pub/data/noaa/

Downloaded the *.csv and put it into the directory.

The stations of interest are:
1. Chicago
KORD
725300 94846 CHICAGO O'HARE INTERNATIONAL  US   IL KORD  +41.995 -087.934 +0201.8 19461001 20161022
999999 94846 CHICAGO OHARE INTL AP         US   IL KORD  +41.995 -087.934 +0205.4 19700101 19721231

KMDW
725340 14819 CHICAGO MIDWAY INTL ARPT      US   IL KMDW  +41.786 -087.752 +0186.5 19730101 20161022
999999 14819 CHICAGO MIDWAY AP             US   IL KMDW  +41.786 -087.752 +0188.4 19480101 19721231

KGYY
725337 04807 GARY/CHICAGO AIRPORT          US   IN KGYY  +41.617 -087.417 +0180.1 20060101 20161022
725337 99999 GARY CHICAGO                  US   IN KGYY  +41.617 -087.400 +0180.0 19810126 20051231

2. St. Louis
KSTL
724340 13994 LAMBERT-ST LOUIS INTERNATIONA US   MO KSTL  +38.753 -090.374 +0161.9 19730101 20161022
999999 13994 ST LOUIS LAMBERT INT'L ARPT   US   MO KSTL  +38.753 -090.374 +0216.4 19450101 19721231

KSUS
724345 03966 SPIRIT OF ST LOUIS AIRPORT    US   MO KSUS  +38.657 -090.656 +0140.8 19730101 20161022

KCPS
725314 03960 ST LOUIS DOWNTOWN AIRPORT     US   IL KCPS  +38.571 -090.157 +0125.9 20060101 20161022
725314 99999 CAHOKIA/ST. LOUIS             US   IL KCPS  +38.567 -090.150 +0126.0 19781219 20051231

Downloaded these archived files and put them into the directory.
It looks like the files are binaries produced with the help of
a Fortran program.

However! We now know the names and codes for the stations and their datasets, let's try retrieving the data through the web-service. The token is free (but it should be activated).

NOAA cdo http://www.ncdc.noaa.gov/cdo-web/token
 documentation http://www.ncdc.noaa.gov/cdo-web/webservices/v2
Token:	NbgcGSTExtVsfjGNSVmUJxsYtRykAPLc



```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
